### PR TITLE
Added User-Agent header [unitaryhack]

### LINKED ISSUE #91: Add a user-agent string
### What is the desired enhancement?
Every net-friendly tool should use user agents

Add a valid user-agent header that indicates the request is from qiskit_ionq, and a particular version

### PR DESCRIPTION
**Pull request by WingCode**
### Summary
Added User-Agent string.
closes #91 

### Details and comments
An observation, the naming of User-Agent strings is not [standardised](https://webaim.org/blog/user-agent-string-history/).

### CODE REVIEW

**Comment by ColemanCollins** [comment]
Hey @WingCode, thanks for your PR. Per the original issue, one of the things we want in a successful PR here is a bit more information of the rest of the stack being used on submission, including versions. This allows for much more robust debugging and feature detection than just the provider's name.

I'm imagining a good solution here would include at least these three things:
- Provider Version (`qiskit-ionq/0.3.3`)
- Qiskit Terra Version (`qiskit-terra/0.20.2)
- Python Version (`python/3.8.9`)

**Review by ColemanCollins — CHANGES_REQUESTED** [review]
Hey @WingCode, thanks for your PR. It's a great start. Per the original issue, one of the things we want in a successful PR here is a bit more information of the rest of the stack being used on submission, including versions. This allows for much more robust debugging and feature detection than just the provider's name.

I'm imagining a good solution here would include at least these three things:
- Provider Version (`qiskit-ionq/0.3.3`)
- Qiskit Terra Version (`qiskit-terra/0.20.2`)
- Python Version (`python/3.8.9`)

**Comment by ColemanCollins** [comment]
n.b. it probably makes sense to do this as you're building the client instance, instead of on submission.

**Comment by WingCode** [comment]
@ColemanCollins Thank you for the great inputs!

> I'm imagining a good solution here would include at least these three things:
> 
> * Provider Version (`qiskit-ionq/0.3.3`)
> * Qiskit Terra Version (`qiskit-terra/0.20.2`)
> * Python Version (`python/3.8.9`)

Can we also add the OS name to the user-agent string using `platform.system()` ?

**Review by ColemanCollins — CHANGES_REQUESTED** [review]
Hey @WingCode, thanks for the great update. One minor cleanup thing and we're good here.

Also would appreciate if you added a quick test for this behavior (just confirm a generated request includes the substring of the package's own version or something) but this is simple enough that I'm not going to require it + want to make sure this gets in before Friday so you can get credit as part of unitaryHACK

**Review by ColemanCollins — APPROVED** [review]
Great stuff! thanks so much for your effort and contributions here

**Pull request merged**
